version: "3.7"
services:
  bot:
    container_name: messenger-bot
    build:
      context: .
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
networks:
  default:
    name: web-dev_app-network
